name: go

on:
  push:
    branches:
      - main
    tags:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Linters (Static Analysis) for Go
    steps:
      - name: Checkout code into the Go module directory.
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x

      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Linting & vetting.
        env:
          GOBIN: /tmp/.bin
        run: make lint
  test:
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        go: ['1.18.x']
        platform: [ubuntu-latest]

    name: Test apps on Go ${{ matrix.go }} ${{ matrix.platform }}
    steps:
      - name: Checkout code into the Go module directory.
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Test
        env:
          GOBIN: /tmp/.bin
        run: make test
